<?php

namespace Database\Seeders;

use App\Support\RoleRegistry;
use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;
use Spatie\Permission\PermissionRegistrar;

class RoleSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        app(PermissionRegistrar::class)->forgetCachedPermissions();

        $permissions = [
            'dashboard.admin.view',
            'dashboard.manager.view',
            'dashboard.teacher.view',
            'dashboard.parent.view',
            'dashboard.student.view',
            'users.view',
            'users.create',
            'users.update',
            'users.delete',
            'roles.manage',
            'parents.view',
            'parents.create',
            'parents.update',
            'parents.delete',
            'teachers.view',
            'teachers.create',
            'teachers.update',
            'teachers.delete',
            'students.view',
            'students.create',
            'students.update',
            'students.delete',
            'students.photo.update',
            'students.files.manage',
            'courses.view',
            'courses.create',
            'courses.update',
            'courses.delete',
            'groups.view',
            'groups.create',
            'groups.update',
            'groups.delete',
            'group-schedules.manage',
            'enrollments.view',
            'enrollments.create',
            'enrollments.update',
            'enrollments.delete',
            'attendance.student.view',
            'attendance.student.take',
            'attendance.teacher.view',
            'attendance.teacher.take',
            'memorization.view',
            'memorization.record',
            'memorization.override-duplicate-page',
            'quran-tests.view',
            'quran-tests.record',
            'quran-tests.override-progression',
            'points.view',
            'points.create-manual',
            'points.void',
            'activities.view',
            'activities.create',
            'activities.update',
            'activities.delete',
            'activities.finance.view',
            'activities.registrations.manage',
            'activities.expenses.manage',
            'activities.payments.manage',
            'invoices.view',
            'invoices.create',
            'invoices.update',
            'invoices.delete',
            'payments.view',
            'payments.create',
            'payments.void',
            'assessments.view',
            'assessments.create',
            'assessments.update',
            'assessments.delete',
            'assessment-results.view',
            'assessment-results.record',
            'assessment-score-bands.view',
            'assessment-score-bands.manage',
            'reports.view',
            'settings.manage',
            'website.manage',
            'student-notes.view',
            'student-notes.create',
            'student-notes.update',
            'student-notes.delete',
        ];

        foreach ($permissions as $permissionName) {
            Permission::findOrCreate($permissionName, 'web');
        }

        $roles = [
            RoleRegistry::SUPER_ADMIN => $permissions,
            RoleRegistry::ADMIN => $permissions,
            RoleRegistry::MANAGER => [
                'dashboard.manager.view',
                'parents.view',
                'parents.create',
                'parents.update',
                'parents.delete',
                'teachers.view',
                'teachers.create',
                'teachers.update',
                'teachers.delete',
                'students.view',
                'students.create',
                'students.update',
                'students.delete',
                'students.photo.update',
                'students.files.manage',
                'courses.view',
                'courses.create',
                'courses.update',
                'courses.delete',
                'groups.view',
                'groups.create',
                'groups.update',
                'groups.delete',
                'group-schedules.manage',
                'enrollments.view',
                'enrollments.create',
                'enrollments.update',
                'enrollments.delete',
                'attendance.student.view',
                'attendance.student.take',
                'attendance.teacher.view',
                'attendance.teacher.take',
                'memorization.view',
                'memorization.record',
                'memorization.override-duplicate-page',
                'quran-tests.view',
                'quran-tests.record',
                'quran-tests.override-progression',
                'points.view',
                'points.create-manual',
                'points.void',
                'activities.view',
                'activities.create',
                'activities.update',
                'activities.delete',
                'activities.finance.view',
                'activities.registrations.manage',
                'activities.expenses.manage',
                'activities.payments.manage',
                'invoices.view',
                'invoices.create',
                'invoices.update',
                'invoices.delete',
                'payments.view',
                'payments.create',
                'payments.void',
                'assessments.view',
                'assessments.create',
                'assessments.update',
                'assessments.delete',
                'assessment-results.view',
                'assessment-results.record',
                'assessment-score-bands.view',
                'assessment-score-bands.manage',
                'reports.view',
                'settings.manage',
                'website.manage',
                'student-notes.view',
                'student-notes.create',
                'student-notes.update',
                'student-notes.delete',
            ],
            RoleRegistry::TEACHER => [
                'dashboard.teacher.view',
                'students.view',
                'groups.view',
                'enrollments.view',
                'attendance.student.view',
                'attendance.student.take',
                'memorization.view',
                'memorization.record',
                'quran-tests.view',
                'quran-tests.record',
                'points.view',
                'assessments.view',
                'assessments.create',
                'assessments.update',
                'assessment-results.view',
                'assessment-results.record',
                'student-notes.view',
                'student-notes.create',
                'student-notes.update',
                'student-notes.delete',
            ],
            RoleRegistry::PARENT => [
                'dashboard.parent.view',
                'students.view',
                'enrollments.view',
                'memorization.view',
                'quran-tests.view',
                'points.view',
                'invoices.view',
                'payments.view',
            ],
            RoleRegistry::STUDENT => [
                'dashboard.student.view',
                'students.view',
                'enrollments.view',
                'memorization.view',
                'quran-tests.view',
                'points.view',
            ],
        ];

        foreach ($roles as $roleName => $rolePermissions) {
            $role = Role::findOrCreate($roleName, 'web');
            $role->syncPermissions($rolePermissions);
        }

        app(PermissionRegistrar::class)->forgetCachedPermissions();
    }
}
