<x-platform-layout title="Platform access">
    <header><p class="text-sm font-medium text-emerald-700">Platform administration</p><h1 class="mt-1 text-3xl font-bold">Roles and users</h1><p class="mt-2 text-zinc-600">Create Platform roles, assign only the permissions needed, and manage Platform users.</p></header>
    @if(auth('platform')->user()->isPlatformOwner())
    <section class="grid gap-6 xl:grid-cols-2">
        <div class="rounded-3xl border bg-white p-6 shadow-sm"><h2 class="text-lg font-semibold">Create a role</h2><p class="mt-1 text-sm text-zinc-500">Roles are for Platform management only. They do not affect tenant roles.</p><form method="POST" action="{{ route('platform.access.roles.store') }}" class="mt-5 space-y-4">@csrf
            <input name="name" required placeholder="Role name" class="w-full rounded-xl border p-3" value="{{ old('name') }}"><textarea name="description" placeholder="What this role is responsible for" class="w-full rounded-xl border p-3">{{ old('description') }}</textarea>
            <div class="grid gap-2 sm:grid-cols-2">@foreach($permissions as $permission)<label class="flex gap-2 rounded-xl border p-3 text-sm"><input type="checkbox" name="permissions[]" value="{{ $permission->id }}"> <span><strong>{{ $permission->name }}</strong><br><span class="text-zinc-500">{{ $permission->code }}</span></span></label>@endforeach</div>
            <button class="rounded-xl bg-emerald-700 px-4 py-3 font-medium text-white">Create role</button>
        </form></div>
        <div class="rounded-3xl border bg-white p-6 shadow-sm"><h2 class="text-lg font-semibold">Create a Platform user</h2><p class="mt-1 text-sm text-zinc-500">Give the temporary password to the user manually. They must change it at their first login.</p><form method="POST" action="{{ route('platform.access.users.store') }}" class="mt-5 grid gap-4">@csrf
            <input name="name" required placeholder="Full name" class="rounded-xl border p-3" value="{{ old('name') }}"><input name="email" type="email" required placeholder="Email address" class="rounded-xl border p-3" value="{{ old('email') }}"><input name="password" type="password" required placeholder="Temporary password (12+ characters)" class="rounded-xl border p-3"><input name="password_confirmation" type="password" required placeholder="Confirm temporary password" class="rounded-xl border p-3">
            <div class="grid gap-2 sm:grid-cols-2">@foreach($roles as $role)<label class="flex gap-2 rounded-xl border p-3 text-sm"><input type="checkbox" name="roles[]" value="{{ $role->id }}"> {{ $role->name }}@if($role->is_owner)<span class="text-amber-700">(Owner)</span>@endif</label>@endforeach</div>
            <button class="rounded-xl bg-emerald-700 px-4 py-3 font-medium text-white">Create Platform user</button>
        </form></div>
    </section>
    @endif
    <section class="rounded-3xl border bg-white p-6 shadow-sm"><h2 class="text-lg font-semibold">Platform roles</h2><div class="mt-4 space-y-3">@foreach($roles as $role)<details class="rounded-2xl border p-4" @if($role->is_owner) open @endif><summary class="cursor-pointer font-medium">{{ $role->name }} @if($role->is_owner)<span class="ml-2 rounded bg-amber-100 px-2 py-1 text-xs text-amber-800">Owner</span>@endif <span class="ml-2 text-sm font-normal text-zinc-500">{{ $role->administrators_count }} users</span></summary><p class="mt-3 text-sm text-zinc-600">{{ $role->description ?: 'No description' }}</p><p class="mt-3 text-sm"><strong>Permissions:</strong> {{ $role->is_owner ? 'All permissions' : ($role->permissions->pluck('name')->join(', ') ?: 'None') }}</p>@if(auth('platform')->user()->isPlatformOwner() && !$role->is_owner)<form method="POST" action="{{ route('platform.access.roles.update', $role) }}" class="mt-4 space-y-3">@csrf @method('PUT')<input name="name" value="{{ $role->name }}" required class="w-full rounded-xl border p-3"><textarea name="description" class="w-full rounded-xl border p-3">{{ $role->description }}</textarea><div class="grid gap-2 sm:grid-cols-2">@foreach($permissions as $permission)<label class="flex gap-2 rounded-xl border p-3 text-sm"><input type="checkbox" name="permissions[]" value="{{ $permission->id }}" @checked($role->permissions->contains($permission))> {{ $permission->name }}</label>@endforeach</div><div class="flex gap-3"><button class="rounded-xl border px-4 py-2">Save role</button><button formmethod="POST" formaction="{{ route('platform.access.roles.destroy', $role) }}" name="_method" value="DELETE" class="rounded-xl border border-red-300 px-4 py-2 text-red-700" onclick="return confirm('Delete this role?')">Delete role</button></div></form>@endif</details>@endforeach</div></section>
    <section class="rounded-3xl border bg-white p-6 shadow-sm"><h2 class="text-lg font-semibold">Platform users</h2><div class="mt-4 space-y-4">@foreach($administrators as $administrator)<details class="rounded-2xl border p-4"><summary class="cursor-pointer"><strong>{{ $administrator->name }}</strong> <span class="text-zinc-500">{{ $administrator->email }}</span> @if(!$administrator->is_active)<span class="ml-2 text-red-700">Inactive</span>@endif @if($administrator->must_change_password)<span class="ml-2 text-amber-700">Password change required</span>@endif</summary><div class="mt-4 grid gap-5 lg:grid-cols-2"><form method="POST" action="{{ route('platform.access.users.update', $administrator) }}" class="space-y-3">@csrf @method('PUT')<input name="name" value="{{ $administrator->name }}" required class="w-full rounded-xl border p-3"><input name="email" type="email" value="{{ $administrator->email }}" required class="w-full rounded-xl border p-3"><button class="rounded-xl border px-4 py-2">Save details</button></form><div class="space-y-3"><form method="POST" action="{{ route('platform.access.users.password', $administrator) }}" class="space-y-2">@csrf @method('PUT')<input name="password" type="password" required placeholder="New temporary password (12+ characters)" class="w-full rounded-xl border p-3"><input name="password_confirmation" type="password" required placeholder="Confirm password" class="w-full rounded-xl border p-3"><button class="rounded-xl border px-4 py-2">Reset password</button></form><form method="POST" action="{{ route('platform.access.users.status', $administrator) }}">@csrf @method('PATCH')<input type="hidden" name="is_active" value="{{ $administrator->is_active ? 0 : 1 }}"><button class="rounded-xl border px-4 py-2 {{ $administrator->is_active ? 'text-red-700' : 'text-emerald-700' }}">{{ $administrator->is_active ? 'Deactivate user' : 'Activate user' }}</button></form></div></div>@if(auth('platform')->user()->isPlatformOwner())<form method="POST" action="{{ route('platform.access.users.roles', $administrator) }}" class="mt-4 border-t pt-4">@csrf @method('PUT')<p class="mb-2 text-sm font-medium">Roles</p><div class="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">@foreach($roles as $role)<label class="flex gap-2 text-sm"><input type="checkbox" name="roles[]" value="{{ $role->id }}" @checked($administrator->roles->contains($role))> {{ $role->name }}</label>@endforeach</div><button class="mt-3 rounded-xl border px-4 py-2">Save roles</button></form>@endif</details>@endforeach</div></section>
</x-platform-layout>
