<div class="grid gap-3 sm:grid-cols-2" data-data-quality-parent-editor>
    <div><label class="mb-1 block text-sm">{{ __('data_governance.quality.fields.father_name') }}</label><input wire:model="editableRecords.{{ $index }}.father_name" @unless($manualSave ?? false) wire:change="autosaveRecord({{ $index }})" @endunless type="text" class="w-full rounded-xl px-4 py-3 text-sm">@error("editableRecords.$index.father_name")<div class="mt-1 text-xs text-red-300">{{ $message }}</div>@enderror</div>
    <div><label class="mb-1 block text-sm">{{ __('data_governance.quality.fields.father_work') }}</label><input wire:model="editableRecords.{{ $index }}.father_work" @unless($manualSave ?? false) wire:change="autosaveRecord({{ $index }})" @endunless type="text" class="w-full rounded-xl px-4 py-3 text-sm"></div>
    <div><label class="mb-1 block text-sm">{{ __('data_governance.quality.fields.father_phone') }}</label><input wire:model="editableRecords.{{ $index }}.father_phone" @unless($manualSave ?? false) wire:change="autosaveRecord({{ $index }})" @endunless type="tel" class="w-full rounded-xl px-4 py-3 text-sm" dir="ltr"></div>
    <div><label class="mb-1 block text-sm">{{ __('data_governance.quality.fields.mother_name') }}</label><input wire:model="editableRecords.{{ $index }}.mother_name" @unless($manualSave ?? false) wire:change="autosaveRecord({{ $index }})" @endunless type="text" class="w-full rounded-xl px-4 py-3 text-sm"></div>
    <div><label class="mb-1 block text-sm">{{ __('data_governance.quality.fields.mother_phone') }}</label><input wire:model="editableRecords.{{ $index }}.mother_phone" @unless($manualSave ?? false) wire:change="autosaveRecord({{ $index }})" @endunless type="tel" class="w-full rounded-xl px-4 py-3 text-sm" dir="ltr"></div>
    <div><label class="mb-1 block text-sm">{{ __('data_governance.quality.fields.home_phone') }}</label><input wire:model="editableRecords.{{ $index }}.home_phone" @unless($manualSave ?? false) wire:change="autosaveRecord({{ $index }})" @endunless type="tel" class="w-full rounded-xl px-4 py-3 text-sm" dir="ltr"></div>
    <div class="sm:col-span-2"><label class="mb-1 block text-sm">{{ __('data_governance.quality.fields.address') }}</label><input wire:model="editableRecords.{{ $index }}.address" @unless($manualSave ?? false) wire:change="autosaveRecord({{ $index }})" @endunless type="text" class="w-full rounded-xl px-4 py-3 text-sm"></div>
    @if ($record['has_user'])<div class="sm:col-span-2"><label class="mb-1 block text-sm">{{ __('data_governance.quality.fields.email') }}</label><input wire:model="editableRecords.{{ $index }}.email" @unless($manualSave ?? false) wire:change="autosaveRecord({{ $index }})" @endunless type="email" class="w-full rounded-xl px-4 py-3 text-sm" dir="ltr">@error("editableRecords.$index.email")<div class="mt-1 text-xs text-red-300">{{ $message }}</div>@enderror</div>@endif
</div>
