<!doctype html>
<html lang="ar" dir="rtl"><head><meta charset="utf-8"><style>
@page{margin:25mm 14mm 18mm;header:pdf-header;footer:pdf-footer}body{font-family:dubai,sans-serif;color:#17231b;font-size:11px;font-weight:400}.meta{text-align:center;margin-bottom:14px;color:#4b5d50;font-weight:300}table{width:100%;border-collapse:collapse}th,td{border:1px solid #aebbb1;padding:7px;text-align:right}th{background:#dfece2;font-weight:700;text-align:center;border-bottom:3px double #aebbb1}thead{display:table-header-group}tbody tr:nth-child(even) td{background:#f1f7f2}.pdf-header,.pdf-footer{background:#cfe7d6;padding:2mm 3mm}.pdf-header img{height:auto;max-height:23mm;max-width:35mm;width:auto}.header-table{border-collapse:collapse;table-layout:fixed;width:100%}.header-table td{border:0;padding:0;vertical-align:middle}.header-side{width:22%}.header-copy{text-align:center;width:56%}.header-title{font-size:20px;font-weight:700}.header-subtitle{font-size:13px;font-weight:500;margin-top:1mm}.pdf-footer{color:#526158;font-size:9px;text-align:center}
</style></head><body>
<htmlpageheader name="pdf-header"><div class="pdf-header"><table class="header-table" dir="ltr"><tr><td class="header-side"></td><td class="header-copy" dir="rtl"><div class="header-title">بيان الأجزاء المسبورة</div><div class="header-subtitle">{{ $course->name }}</div></td><td class="header-side" dir="rtl">@if($logo)<img src="{{ $logo }}" alt="">@endif</td></tr></table></div></htmlpageheader><htmlpagefooter name="pdf-footer"><div class="pdf-footer">{PAGENO} / {nbpg}</div></htmlpagefooter>
<div class="meta">{{ now()->format('d-m-Y') }} — {{ __('course_end.highlights.final_tests') }}: {{ number_format($rows->count()) }}</div>
<table><thead><tr><th>#</th><th>{{ __('course_end.table.name') }}</th><th>{{ __('course_end.table.juz') }}</th><th>{{ __('course_end.table.mark') }}</th><th>{{ __('course_end.table.grade') }}</th></tr></thead><tbody>
@foreach($rows as $row)@php($score = (float) $row['mark'])<tr><td>{{ $loop->iteration }}</td><td>{{ $row['name'] }}</td><td>{{ $row['juz'] }}</td><td>{{ \App\Support\PercentageFormatter::format($row['mark']) }}</td><td>{{ $score >= 95 ? __('course_end.grades.excellent') : ($score >= 90 ? __('course_end.grades.very_good') : ($score >= 85 ? __('course_end.grades.good') : ($score >= 80 ? __('course_end.grades.acceptable') : __('course_end.grades.below_acceptable')))) }}</td></tr>@endforeach
</tbody></table></body></html>
