<!doctype html>
<html lang="{{ app()->getLocale() }}" dir="{{ app()->isLocale('ar') ? 'rtl' : 'ltr' }}"><head><meta charset="utf-8"><style>
@page{margin:31mm 14mm 18mm;header:pdf-header;footer:pdf-footer}@page :first{header:pdf-first-header}body{font-family:dubai,sans-serif;color:#17231b;font-size:11px;font-weight:400}table{width:100%;border-collapse:collapse}th,td{border:1px solid #aebbb1;padding:7px;text-align:{{ app()->isLocale('ar') ? 'right' : 'left' }}}th{background:#dfece2;font-weight:700;text-align:center;border-bottom:3px double #aebbb1}thead{display:table-header-group}tbody tr:nth-child(even) td{background:#f1f7f2}.pdf-header,.pdf-footer{background:#cfe7d6;padding:2mm 3mm}.pdf-header img{height:auto;max-height:23mm;max-width:35mm;width:auto}.header-table{border-collapse:collapse;table-layout:fixed;width:100%}.header-table td{border:0;padding:0;vertical-align:middle}.header-side{width:22%}.header-copy{text-align:center;width:56%}.header-title{font-size:20px;font-weight:700}.header-subtitle{font-size:13px;font-weight:500;margin-top:1mm}.header-meta{font-size:9px}.meta-line{display:block;overflow:hidden;white-space:nowrap}.meta-label{float:{{ app()->isLocale('ar') ? 'right' : 'left' }}}.meta-value{direction:ltr;float:{{ app()->isLocale('ar') ? 'left' : 'right' }}}.continued{color:#607064;font-size:8px;margin-top:1mm;text-align:center}.report-table{margin-top:4mm}.pdf-footer{color:#526158;font-size:9px;text-align:center}
</style></head><body>
@php($headerMeta = '<div class="meta-line"><span class="meta-label">'.__('course_end.date_label').'</span><span class="meta-value">'.now()->format('d-m-Y').'</span></div><div class="meta-line"><span class="meta-label">'.__('course_end.final_tests_total').'</span><span class="meta-value">'.number_format($rows->count()).'</span></div>')
<htmlpageheader name="pdf-first-header"><div class="pdf-header"><table class="header-table" dir="ltr"><tr><td class="header-side header-meta" dir="{{ app()->isLocale('ar') ? 'rtl' : 'ltr' }}">{!! $headerMeta !!}</td><td class="header-copy" dir="{{ app()->isLocale('ar') ? 'rtl' : 'ltr' }}"><div class="header-title">{{ __('course_end.final_tests_report_title') }}</div><div class="header-subtitle">{{ $course->name }}</div></td><td class="header-side" dir="rtl">@if($logo)<img src="{{ $logo }}" alt="">@endif</td></tr></table></div></htmlpageheader>
<htmlpageheader name="pdf-header"><div class="pdf-header"><table class="header-table" dir="ltr"><tr><td class="header-side header-meta" dir="{{ app()->isLocale('ar') ? 'rtl' : 'ltr' }}">{!! $headerMeta !!}<div class="continued">{{ __('course_end.continued') }}</div></td><td class="header-copy" dir="{{ app()->isLocale('ar') ? 'rtl' : 'ltr' }}"><div class="header-title">{{ __('course_end.final_tests_report_title') }}</div><div class="header-subtitle">{{ $course->name }}</div></td><td class="header-side" dir="rtl">@if($logo)<img src="{{ $logo }}" alt="">@endif</td></tr></table></div></htmlpageheader>
<htmlpagefooter name="pdf-footer"><div class="pdf-footer" dir="ltr">{PAGENO} / {nbpg}</div></htmlpagefooter>
<table class="report-table"><thead><tr><th>#</th><th>{{ __('course_end.table.name') }}</th><th>{{ __('course_end.table.juz') }}</th><th>{{ __('course_end.table.mark') }}</th><th>{{ __('course_end.table.grade') }}</th></tr></thead><tbody>
@foreach($rows as $row)@php($score = (float) $row['mark'])<tr><td>{{ $loop->iteration }}</td><td>{{ $row['name'] }}</td><td>{{ $row['juz'] }}</td><td>{{ \App\Support\PercentageFormatter::format($row['mark']) }}</td><td>{{ $score >= 95 ? __('course_end.grades.excellent') : ($score >= 90 ? __('course_end.grades.very_good') : ($score >= 85 ? __('course_end.grades.good') : ($score >= 80 ? __('course_end.grades.acceptable') : __('course_end.grades.below_acceptable')))) }}</td></tr>@endforeach
</tbody></table></body></html>
