<!doctype html>
<html lang="{{ app()->getLocale() }}" dir="{{ app()->isLocale('ar') ? 'rtl' : 'ltr' }}"><head><meta charset="utf-8"><style>
@page{margin:35mm 14mm 18mm;header:pdf-header;footer:pdf-footer}@page :first{header:pdf-first-header}body{font-family:dubai,sans-serif;color:#17231b;font-size:11px;font-weight:400}table{width:100%;border-collapse:collapse}th,td{border:1px solid #aebbb1;padding:7px;text-align:{{ app()->isLocale('ar') ? 'right' : 'left' }}}th{background:#dfece2;font-weight:bold;text-align:center;border-bottom:3px double #aebbb1}.report-table thead tr:not(.report-page-gap) th{font-family:dubai,sans-serif;font-weight:bold}.report-page-gap th{background:#fff;border:0;font-size:0;height:4mm;line-height:4mm;padding:0}thead{display:table-header-group}tbody tr:nth-child(even) td{background:#f1f7f2}.pdf-header,.pdf-footer{background:#cfe7d6;padding:2mm 3mm}.pdf-header img{height:auto;max-height:23mm;max-width:35mm;width:auto}.header-table{border-collapse:collapse;table-layout:fixed;width:100%}.header-table td{border:0;padding:0;vertical-align:middle}.header-side{width:22%}.header-copy{text-align:center;width:56%}.header-title{font-family:dubai,sans-serif;font-size:20px;font-weight:bold}.header-subtitle{font-size:13px;font-weight:500;margin-top:1mm}.header-meta{font-size:9px}.header-meta[dir=rtl]{position:relative;left:-2mm}.header-meta-table{table-layout:fixed;width:100%}.header-meta-table td{border:0;padding:0 0 0.8mm;white-space:nowrap}.meta-label{font-family:dubaimedium,sans-serif;font-weight:normal;width:58%}.meta-value{direction:ltr;width:42%}.header-meta[dir=rtl] .meta-label{text-align:left;padding-left:.8mm}.header-meta[dir=rtl] .meta-value{text-align:right;padding-right:.8mm}.header-meta[dir=ltr] .meta-label{text-align:right;padding-right:.8mm}.header-meta[dir=ltr] .meta-value{text-align:left;padding-left:.8mm}.continued{color:#607064;font-size:8px;margin-top:1mm;text-align:center}.pdf-footer{color:#526158;font-size:9px;text-align:center}
</style></head><body>
@php
    $metaLabelStyle = app()->isLocale('ar') ? 'text-align:left;padding-left:.8mm' : 'text-align:right;padding-right:.8mm';
    $metaValueStyle = app()->isLocale('ar') ? 'text-align:right;padding-right:.8mm' : 'text-align:left;padding-left:.8mm';
    $headerMeta = '<table class="header-meta-table"><tr><td class="meta-label" style="'.$metaLabelStyle.'">'.__('course_end.date_label').'</td><td class="meta-value" style="'.$metaValueStyle.'">'.now()->format('d-m-Y').'</td></tr><tr><td class="meta-label" style="'.$metaLabelStyle.'">'.__('course_end.final_tests_total').'</td><td class="meta-value" style="'.$metaValueStyle.'">'.number_format($rows->count()).'</td></tr></table>';
@endphp
<htmlpageheader name="pdf-first-header"><div class="pdf-header"><table class="header-table" dir="ltr"><tr><td class="header-side header-meta" dir="{{ app()->isLocale('ar') ? 'rtl' : 'ltr' }}">{!! $headerMeta !!}</td><td class="header-copy" dir="{{ app()->isLocale('ar') ? 'rtl' : 'ltr' }}"><div class="header-title">{{ __('course_end.final_tests_report_title') }}</div><div class="header-subtitle">{{ $course->name }}</div></td><td class="header-side" dir="rtl">@if($logo)<img src="{{ $logo }}" alt="">@endif</td></tr></table></div></htmlpageheader>
<htmlpageheader name="pdf-header"><div class="pdf-header"><table class="header-table" dir="ltr"><tr><td class="header-side header-meta" dir="{{ app()->isLocale('ar') ? 'rtl' : 'ltr' }}">{!! $headerMeta !!}<div class="continued">{{ __('course_end.continued') }}</div></td><td class="header-copy" dir="{{ app()->isLocale('ar') ? 'rtl' : 'ltr' }}"><div class="header-title">{{ __('course_end.final_tests_report_title') }}</div><div class="header-subtitle">{{ $course->name }}</div></td><td class="header-side" dir="rtl">@if($logo)<img src="{{ $logo }}" alt="">@endif</td></tr></table></div></htmlpageheader>
<htmlpagefooter name="pdf-footer"><div class="pdf-footer" dir="ltr">{PAGENO} / {nbpg}</div></htmlpagefooter>
<table class="report-table"><thead><tr class="report-page-gap"><th colspan="5">&nbsp;</th></tr><tr><th>#</th><th>{{ __('course_end.table.name') }}</th><th>{{ __('course_end.table.juz') }}</th><th>{{ __('course_end.table.mark') }}</th><th>{{ __('course_end.table.grade') }}</th></tr></thead><tbody>
@foreach($rows as $row)<tr><td>{{ $loop->iteration }}</td><td>{{ $row['name'] }}</td><td>{{ $row['juz'] }}</td><td>{{ \App\Support\PercentageFormatter::format($row['mark']) }}</td><td>{{ __('course_end.grades.'.($row['grade'] ?? \App\Services\CourseEndService::finalTestGradeKey((float) $row['mark']))) }}</td></tr>@endforeach
</tbody></table></body></html>
