@php($canManageSubscriptions = auth('platform')->user()->hasPlatformPermission('manage.subscriptions'))
<x-platform.tenant-workspace :tenant="$tenant" current="billing">
    <div class="space-y-6">
        <section class="rounded-3xl border bg-white p-6 shadow-sm"><div class="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><h2 class="text-xl font-bold">Payments and balance</h2><p class="mt-1 text-sm text-zinc-500">Record money received offline. Credit stays on the tenant account and is used for activation and automatic renewals.</p></div><div class="rounded-2xl bg-emerald-50 px-5 py-3 text-right"><div class="text-xs text-emerald-700">Current balance</div><div class="text-xl font-bold text-emerald-950">{{ number_format($billingBalance) }} SYP</div></div></div>
            @if($canManageSubscriptions)<form method="POST" action="{{ route('platform.tenants.subscription.payments.store', $tenant) }}" class="mt-6 grid gap-4 md:grid-cols-2">@csrf
                <label class="grid gap-1.5 text-sm font-semibold">Amount (SYP)<input type="number" name="amount_syp" min="1" required class="rounded-xl border p-3 font-normal"></label><label class="grid gap-1.5 text-sm font-semibold">Payment method<select name="payment_method" required class="rounded-xl border p-3 font-normal"><option value="cash">Cash</option><option value="bank_transfer">Bank transfer</option><option value="cheque">Cheque</option><option value="other">Other</option></select></label>
                <label class="grid gap-1.5 text-sm font-semibold">Paid at<input type="datetime-local" name="paid_at" value="{{ now()->format('Y-m-d\TH:i') }}" required class="rounded-xl border p-3 font-normal"></label><label class="grid gap-1.5 text-sm font-semibold">Reference<input name="reference" required maxlength="100" class="rounded-xl border p-3 font-normal" placeholder="Receipt or transfer reference"></label>
                <label class="grid gap-1.5 text-sm font-semibold md:col-span-2">Note<textarea name="note" rows="2" class="rounded-xl border p-3 font-normal"></textarea></label><div class="md:col-span-2"><button class="rounded-xl bg-zinc-950 px-5 py-3 font-bold text-white">Record payment</button></div>
            </form>@endif
        </section>
        <section class="overflow-hidden rounded-3xl border bg-white shadow-sm"><div class="border-b p-6"><h2 class="text-xl font-bold">Account history</h2></div><div class="overflow-x-auto"><table class="w-full text-left text-sm"><thead class="bg-zinc-50 text-xs uppercase text-zinc-500"><tr><th class="px-6 py-3">Date</th><th class="px-6 py-3">Type</th><th class="px-6 py-3">Reference</th><th class="px-6 py-3 text-right">Credit</th><th class="px-6 py-3 text-right">Debit</th></tr></thead><tbody class="divide-y">@forelse($billingEntries as $entry)<tr><td class="px-6 py-4">{{ ($entry->paid_at ?? $entry->created_at)->format('Y-m-d H:i') }}</td><td class="px-6 py-4 font-medium">{{ str($entry->type)->replace('_', ' ')->title() }}</td><td class="px-6 py-4 text-zinc-500">{{ $entry->reference ?? $entry->receipt_number ?? '—' }}</td><td class="px-6 py-4 text-right text-emerald-700">{{ $entry->credit_syp ? number_format($entry->credit_syp) : '—' }}</td><td class="px-6 py-4 text-right text-red-700">{{ $entry->debit_syp ? number_format($entry->debit_syp) : '—' }}</td></tr>@empty<tr><td colspan="5" class="px-6 py-8 text-center text-zinc-500">No payments or charges yet.</td></tr>@endforelse</tbody></table></div></section>
    </div>
</x-platform.tenant-workspace>
