@php($canManageSubscriptions = auth('platform')->user()->hasPlatformPermission('manage.subscriptions'))
<x-platform.tenant-workspace :tenant="$tenant" current="billing">
    <div class="space-y-6">
        <section class="rounded-3xl border bg-white p-6 shadow-sm"><div class="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><h2 class="text-xl font-bold">{{ __('platform.ui.billing.title') }}</h2><p class="mt-1 text-sm text-zinc-500">{{ __('platform.ui.billing.description') }}</p></div><div class="rounded-2xl bg-emerald-50 px-5 py-3 text-end"><div class="text-xs text-emerald-700">{{ __('platform.ui.billing.current_balance') }}</div><div class="text-xl font-bold text-emerald-950" dir="ltr">{{ number_format($billingBalance) }} SYP</div></div></div>
            @if($canManageSubscriptions)<form method="POST" action="{{ route('platform.tenants.subscription.payments.store', $tenant) }}" class="mt-6 grid gap-4 md:grid-cols-2">@csrf
                <label class="grid gap-1.5 text-sm font-semibold">{{ __('platform.ui.billing.amount') }}<input type="number" name="amount_syp" min="1" required class="rounded-xl border p-3 font-normal"></label><label class="grid gap-1.5 text-sm font-semibold">{{ __('platform.ui.billing.payment_method') }}<select name="payment_method" required class="rounded-xl border p-3 font-normal"><option value="cash">{{ __('platform.ui.billing.cash') }}</option><option value="bank_transfer">{{ __('platform.ui.billing.bank_transfer') }}</option><option value="cheque">{{ __('platform.ui.billing.cheque') }}</option><option value="other">{{ __('platform.ui.billing.other') }}</option></select></label>
                <label class="grid gap-1.5 text-sm font-semibold">{{ __('platform.ui.billing.paid_at') }}<input type="datetime-local" name="paid_at" value="{{ now()->format('Y-m-d\TH:i') }}" required class="rounded-xl border p-3 font-normal"></label><label class="grid gap-1.5 text-sm font-semibold">{{ __('platform.ui.common.reference') }}<input name="reference" required maxlength="100" class="rounded-xl border p-3 font-normal" placeholder="{{ __('platform.ui.billing.reference_placeholder') }}"></label>
                <label class="grid gap-1.5 text-sm font-semibold md:col-span-2">{{ __('platform.ui.billing.note') }}<textarea name="note" rows="2" class="rounded-xl border p-3 font-normal"></textarea></label><div class="md:col-span-2"><button class="rounded-xl bg-zinc-950 px-5 py-3 font-bold text-white">{{ __('platform.ui.billing.record') }}</button></div>
            </form>@endif
        </section>
        <section class="overflow-hidden rounded-3xl border bg-white shadow-sm"><div class="border-b p-6"><h2 class="text-xl font-bold">{{ __('platform.ui.billing.history') }}</h2></div><div class="overflow-x-auto"><table class="w-full text-start text-sm"><thead class="bg-zinc-50 text-xs uppercase text-zinc-500"><tr><th class="px-6 py-3">{{ __('platform.ui.common.date') }}</th><th class="px-6 py-3">{{ __('platform.ui.common.type') }}</th><th class="px-6 py-3">{{ __('platform.ui.common.reference') }}</th><th class="px-6 py-3 text-end">{{ __('platform.ui.billing.credit') }}</th><th class="px-6 py-3 text-end">{{ __('platform.ui.billing.debit') }}</th></tr></thead><tbody class="divide-y">@forelse($billingEntries as $entry)<tr><td class="px-6 py-4" dir="ltr">{{ ($entry->paid_at ?? $entry->created_at)->format('Y-m-d H:i') }}</td><td class="px-6 py-4 font-medium">{{ __('platform.ui.events.'.$entry->type) }}</td><td class="px-6 py-4 text-zinc-500">{{ $entry->reference ?? $entry->receipt_number ?? '—' }}</td><td class="px-6 py-4 text-end text-emerald-700">{{ $entry->credit_syp ? number_format($entry->credit_syp) : '—' }}</td><td class="px-6 py-4 text-end text-red-700">{{ $entry->debit_syp ? number_format($entry->debit_syp) : '—' }}</td></tr>@empty<tr><td colspan="5" class="px-6 py-8 text-center text-zinc-500">{{ __('platform.ui.billing.empty') }}</td></tr>@endforelse</tbody></table></div></section>
    </div>
</x-platform.tenant-workspace>
