@php
    $moduleNames = collect($moduleCatalog)->mapWithKeys(fn ($module) => [$module['code'] => $module['name']]);
    $selectedExtras = old('modules', $moduleSnapshot['extras']);
    $modulePreview = session('module_preview');
    $canManageTenant = auth('platform')->user()->hasPlatformPermission('manage.tenants');
@endphp
<x-platform.tenant-workspace :tenant="$tenant" current="modules">
    <div class="space-y-6"><section class="rounded-3xl border bg-white p-6 shadow-sm"><div><p class="text-xs font-semibold uppercase tracking-wider text-emerald-700">{{ __('platform.ui.modules.eyebrow') }}</p><h2 class="mt-1 text-xl font-bold">{{ __('platform.ui.modules.title') }}</h2><p class="mt-1 text-sm text-zinc-500">{{ __('platform.ui.modules.description') }}</p></div>
        <form method="POST" action="{{ route('platform.tenants.extras.update', $tenant) }}" class="mt-5 space-y-5">@csrf @method('PUT')<input type="hidden" name="expected_version" value="{{ $moduleSnapshot['version'] }}"><div class="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">@foreach($moduleCatalog as $module) @php($fromPackage = in_array($module['code'], $packageModules, true))<label class="rounded-2xl border p-4 transition {{ $fromPackage ? 'cursor-not-allowed border-zinc-200 bg-zinc-100 text-zinc-500 opacity-75' : ($module['is_available'] && $canManageTenant ? 'cursor-pointer has-[:checked]:border-emerald-500 has-[:checked]:bg-emerald-50' : 'cursor-not-allowed opacity-55') }}" @if($fromPackage) data-package-module-card="{{ $module['code'] }}" @endif><span class="flex items-start gap-3"><input type="checkbox" name="modules[]" value="{{ $module['code'] }}" class="mt-1" @if($fromPackage) data-package-module="{{ $module['code'] }}" @endif @checked($fromPackage || in_array($module['code'], $selectedExtras, true)) @disabled($fromPackage || ! $module['is_available'] || ! $canManageTenant)><span><span class="block font-semibold">{{ $module['name'] }}</span><span class="mt-1 block text-xs text-zinc-500">{{ $fromPackage ? __('platform.ui.modules.included') : __('platform.ui.modules.optional') }}</span></span></span></label>@endforeach</div>
            @if($modulePreview)<div class="rounded-2xl border border-emerald-200 bg-emerald-50 p-4"><h3 class="font-semibold text-emerald-900">{{ __('platform.ui.modules.preview_ready') }}</h3><div class="mt-2 flex flex-wrap gap-2 text-xs">@foreach($modulePreview['added'] as $code)<span class="rounded-full bg-white px-2 py-1 text-emerald-800">+ {{ $moduleNames[$code] ?? $code }}</span>@endforeach @foreach($modulePreview['removed'] as $code)<span class="rounded-full bg-white px-2 py-1 text-red-700">− {{ $moduleNames[$code] ?? $code }}</span>@endforeach @if(!$modulePreview['added'] && !$modulePreview['removed'])<span class="text-emerald-800">{{ __('platform.ui.modules.no_change') }}</span>@endif</div></div>@endif
            @if($canManageTenant)<label class="flex items-start gap-3 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm"><input type="checkbox" name="confirm_extras" value="1" class="mt-1"><span>{{ __('platform.ui.modules.confirmation') }}</span></label><div class="flex flex-col gap-3 sm:flex-row sm:justify-end"><button formaction="{{ route('platform.tenants.extras.preview', $tenant) }}" class="rounded-xl border px-4 py-3">{{ __('platform.ui.modules.preview') }}</button><button class="rounded-xl bg-emerald-700 px-4 py-3 font-semibold text-white">{{ __('platform.ui.modules.save') }}</button></div>@endif</form></section>
        @if($moduleAuditEvents->isNotEmpty())<section class="rounded-3xl border bg-white p-6 shadow-sm"><h2 class="font-semibold">{{ __('platform.ui.modules.recent') }}</h2><div class="mt-4 divide-y">@foreach($moduleAuditEvents as $event)<div class="py-3 text-sm"><div class="flex flex-wrap justify-between gap-2"><span class="font-medium">{{ __('platform.ui.modules.updated') }}</span><time class="text-zinc-500" dir="ltr">{{ $event->created_at->format('Y-m-d H:i') }}</time></div><p class="mt-1 text-zinc-500">{{ __('platform.ui.modules.after_count', ['count' => count($event->properties['after'] ?? [])]) }}</p></div>@endforeach</div></section>@endif
    </div>
</x-platform.tenant-workspace>
