@php($canManageTenant = auth('platform')->user()->hasPlatformPermission('manage.tenants'))
<x-platform.tenant-workspace :tenant="$tenant" current="organisation">
    <div class="space-y-6">
        <section class="rounded-3xl border bg-white p-6 shadow-sm"><h2 class="text-xl font-bold">{{ __('platform.ui.organisation.title') }}</h2><p class="mt-1 text-sm text-zinc-500">{{ __('platform.ui.organisation.description') }}</p>
            <form method="POST" action="{{ route('platform.tenants.update', $tenant) }}" class="mt-6 grid gap-5 md:grid-cols-2">@csrf @method('PUT')
                <label class="grid gap-1.5 text-sm font-semibold">{{ __('platform.ui.organisation.name') }}<input name="name" value="{{ old('name', $tenant->name) }}" required class="rounded-xl border p-3 font-normal">@error('name')<span class="text-xs text-red-700">{{ $message }}</span>@enderror</label>
                <label class="grid gap-1.5 text-sm font-semibold">{{ __('platform.ui.organisation.address') }}<input value="{{ $tenant->slug }}.{{ config('tenancy.base_domain') }}" dir="ltr" readonly class="rounded-xl border bg-zinc-50 p-3 font-normal text-zinc-500"></label>
                <label class="grid gap-1.5 text-sm font-semibold">{{ __('platform.ui.organisation.timezone') }}<select name="timezone" class="rounded-xl border p-3 font-normal"><option value="">{{ __('platform.ui.common.platform_default') }}</option><option value="Asia/Damascus" @selected(old('timezone', $tenant->timezone) === 'Asia/Damascus')>Asia/Damascus</option><option value="UTC" @selected(old('timezone', $tenant->timezone) === 'UTC')>UTC</option></select></label>
                <label class="grid gap-1.5 text-sm font-semibold">{{ __('platform.ui.organisation.language') }}<select name="locale" class="rounded-xl border p-3 font-normal"><option value="">{{ __('platform.ui.common.platform_default') }}</option><option value="ar" @selected(old('locale', $tenant->locale) === 'ar')>{{ __('platform.ui.common.arabic') }}</option><option value="en" @selected(old('locale', $tenant->locale) === 'en')>{{ __('platform.ui.common.english') }}</option></select></label>
                <label class="grid gap-1.5 text-sm font-semibold md:col-span-2">Learning path<input value="{{ $tenant->learningPathLabel() }}" readonly class="rounded-xl border bg-zinc-50 p-3 font-normal text-zinc-500"><span class="text-xs font-normal text-zinc-500">Selected when the tenant was created and cannot be changed.</span></label>
                @if($canManageTenant)<div class="md:col-span-2"><button class="rounded-xl bg-zinc-950 px-5 py-3 font-bold text-white">{{ __('platform.ui.organisation.save') }}</button></div>@endif
            </form>
        </section>
        @if($canManageTenant)<section class="rounded-3xl border bg-white p-6 shadow-sm"><h2 class="text-xl font-bold">{{ __('platform.ui.organisation.reset_title') }}</h2><p class="mt-1 text-sm text-zinc-500">{{ __('platform.ui.organisation.reset_description') }}</p><form method="POST" action="{{ route('platform.tenants.administrator-password', $tenant) }}" class="mt-5 grid gap-4 md:grid-cols-2">@csrf @method('PUT')<input type="password" name="password" required minlength="8" placeholder="{{ __('platform.ui.organisation.temporary_password') }}" class="rounded-xl border p-3"><input type="password" name="password_confirmation" required placeholder="{{ __('platform.ui.organisation.confirm_password') }}" class="rounded-xl border p-3"><div class="md:col-span-2"><button class="rounded-xl border border-zinc-300 px-5 py-3 font-semibold">{{ __('platform.ui.organisation.reset_password') }}</button></div></form></section>@endif
    </div>
</x-platform.tenant-workspace>
