@php($canManageSubscriptions = auth('platform')->user()->hasPlatformPermission('manage.subscriptions'))
<x-platform.tenant-workspace :tenant="$tenant" current="subscription">
    <div class="space-y-6">
        <section class="rounded-3xl border bg-white p-6 shadow-sm"><div class="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><h2 class="text-xl font-bold">Package and subscription</h2><p class="mt-1 text-sm text-zinc-500">The selected package defines both its price and billing period. The tenant does not choose another period.</p></div><div class="rounded-xl bg-zinc-50 px-4 py-2 text-right"><div class="text-xs text-zinc-500">Available balance</div><div class="font-bold">{{ number_format($billingBalance) }} SYP</div></div></div>
            @if($canManageSubscriptions)<form method="POST" action="{{ route('platform.tenants.subscription.update', $tenant) }}" class="mt-6 space-y-5">@csrf @method('PUT')
                <div class="grid gap-5 md:grid-cols-2"><label class="grid gap-1.5 text-sm font-semibold">Package<select name="plan" required data-package class="rounded-xl border p-3 font-normal"><option value="">Choose a package</option>@foreach($plans as $plan)<option value="{{ $plan->code }}" data-price="{{ $plan->price_syp }}" data-days="{{ $plan->billing_period_days }}" @selected(old('plan', $tenant->subscription?->plan?->code) === $plan->code)>{{ $plan->name }} — {{ number_format($plan->price_syp) }} SYP / {{ $plan->billing_period_days }} days</option>@endforeach</select>@error('plan')<span class="text-xs text-red-700">{{ $message }}</span>@enderror</label>
                <label class="grid gap-1.5 text-sm font-semibold">Voucher<select name="voucher_id" data-voucher class="rounded-xl border p-3 font-normal"><option value="">No voucher</option>@foreach($vouchers as $voucher)<option value="{{ $voucher->id }}" data-kind="{{ $voucher->discount_type }}" data-value="{{ $voucher->discount_value }}" @selected((string) old('voucher_id', $tenant->subscription?->subscription_voucher_id) === (string) $voucher->id)>{{ $voucher->code }} — {{ $voucher->name }}</option>@endforeach</select>@error('voucher_id')<span class="text-xs text-red-700">{{ $message }}</span>@enderror</label>
                <label class="grid gap-1.5 text-sm font-semibold">Start date<input type="date" name="starts_at" value="{{ old('starts_at', $tenant->subscription?->starts_at?->format('Y-m-d') ?? now()->format('Y-m-d')) }}" class="rounded-xl border p-3 font-normal"></label>
                <label class="grid gap-1.5 text-sm font-semibold">Activation type<select name="subscription_status" data-activation-type class="rounded-xl border p-3 font-normal"><option value="active" @selected(old('subscription_status', 'active') === 'active')>Paid subscription</option><option value="trial" @selected(old('subscription_status') === 'trial')>Trial period</option></select></label>
                <label data-trial-days class="hidden grid gap-1.5 text-sm font-semibold">Trial length (days)<input type="number" name="trial_days" value="{{ old('trial_days', 14) }}" min="1" max="365" class="rounded-xl border p-3 font-normal"><span class="text-xs font-normal text-zinc-500">Trial length is separate from the package billing period.</span></label>
                <label class="flex items-center gap-3 rounded-xl border p-4 text-sm font-semibold"><input type="checkbox" name="renews_automatically" value="1" @checked(old('renews_automatically', $tenant->subscription?->renews_automatically ?? true))>Renew automatically when the balance is enough</label></div>
                <div class="grid gap-3 rounded-2xl bg-zinc-50 p-5 sm:grid-cols-4"><div><div class="text-xs text-zinc-500">Package price</div><strong data-price-preview>—</strong></div><div><div class="text-xs text-zinc-500">Discount</div><strong data-discount-preview>—</strong></div><div><div class="text-xs text-zinc-500">Charge now</div><strong data-charge-preview>—</strong></div><div><div class="text-xs text-zinc-500">Period</div><strong data-period-preview>—</strong></div></div>
                @error('subscription')<div class="rounded-xl bg-red-50 p-3 text-sm text-red-800">{{ $message }}</div>@enderror
                <button class="rounded-xl bg-emerald-600 px-5 py-3 font-bold text-white">{{ $tenant->subscription ? 'Apply package change' : 'Activate subscription' }}</button>
            </form>@else<div class="mt-6 rounded-2xl bg-zinc-50 p-5 text-sm text-zinc-600">You have read-only access. Current package: <strong>{{ $tenant->subscription?->plan?->name ?? 'Not assigned' }}</strong>.</div>@endif
        </section>
        <section class="rounded-3xl border bg-white p-6 shadow-sm"><h2 class="text-xl font-bold">Package history</h2><div class="mt-4 divide-y">@forelse($history as $event)<div class="py-4"><div class="flex justify-between gap-4"><strong class="text-sm">{{ str($event->event)->replace('_', ' ')->title() }}</strong><time class="text-xs text-zinc-500">{{ $event->created_at->format('Y-m-d H:i') }}</time></div><p class="mt-1 text-xs text-zinc-500">{{ $event->platformAdministrator?->name ?? 'System' }}@if(data_get($event->properties, 'plan')) · {{ data_get($event->properties, 'plan') }}@endif</p></div>@empty<p class="py-5 text-sm text-zinc-500">No package changes yet.</p>@endforelse</div></section>
    </div>
    @if($canManageSubscriptions)<script>document.addEventListener('DOMContentLoaded',()=>{const p=document.querySelector('[data-package]'),v=document.querySelector('[data-voucher]'),a=document.querySelector('[data-activation-type]'),t=document.querySelector('[data-trial-days]');const fmt=n=>new Intl.NumberFormat().format(n)+' SYP';const update=()=>{const po=p.options[p.selectedIndex],vo=v.options[v.selectedIndex],trial=a.value==='trial',price=Number(po?.dataset.price||0),value=Number(vo?.dataset.value||0),discount=trial?0:(vo?.dataset.kind==='percent'?Math.floor(price*value/100):Math.min(price,value)),charge=trial?0:Math.max(0,price-discount);t.classList.toggle('hidden',!trial);document.querySelector('[data-price-preview]').textContent=p.value?fmt(price):'—';document.querySelector('[data-discount-preview]').textContent=p.value?fmt(discount):'—';document.querySelector('[data-charge-preview]').textContent=p.value?fmt(charge):'—';document.querySelector('[data-period-preview]').textContent=p.value?(trial?document.querySelector('[name=trial_days]').value+' trial days':`${po.dataset.days} days`):'—'};[p,v,a,document.querySelector('[name=trial_days]')].forEach(el=>el.addEventListener('change',update));update()})</script>@endif
</x-platform.tenant-workspace>
